# Generated by Django 5.2.17 on 2026-09-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='kind',
            field=models.CharField(choices=[('login', 'signed in'), ('logout', 'signed out'), ('login_failed', 'sign-in refused'), ('session_expired', 'session past its absolute lifetime'), ('invitation_sent', 'invitation issued'), ('invitation_accepted', 'invitation accepted'), ('invitation_refused', 'invitation refused')], db_index=True, max_length=32),
        ),
    ]
