# Generated by Django 5.2.17 on 2026-09-09 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('accounts', '0004_previousemail_and_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='kind',
            field=models.CharField(choices=[('login', 'signed in'), ('logout', 'signed out'), ('login_failed', 'sign-in refused'), ('session_expired', 'session past its absolute lifetime'), ('invitation_sent', 'invitation issued'), ('invitation_accepted', 'invitation accepted'), ('invitation_refused', 'invitation refused'), ('mint', 'executor token minted'), ('mint_refused', 'executor token refused'), ('signup', 'signed up'), ('signup_refused', 'sign-up refused'), ('email_verified', 'email address verified'), ('reauthentication', 'reauthenticated'), ('password_changed', 'password changed'), ('password_reset_requested', 'password reset requested'), ('password_reset', 'password reset'), ('password_pwned', 'password known to Have I Been Pwned'), ('email_changed', 'email address changed'), ('new_device', 'signed in from an unseen device'), ('turnstile_demanded', 'address must now solve Turnstile'), ('google_refused', 'Google sign-in refused'), ('google_connected', 'Google account connected'), ('google_disconnected', 'Google account disconnected')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='EmailAddressAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='added', to='account.emailaddress')),
            ],
        ),
    ]
