# Generated by Django 5.2.17 on 2026-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_google_and_email_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='kind',
            field=models.CharField(choices=[('login', 'signed in'), ('logout', 'signed out'), ('login_failed', 'sign-in refused'), ('session_expired', 'session past its absolute lifetime'), ('invitation_sent', 'invitation issued'), ('invitation_accepted', 'invitation accepted'), ('invitation_refused', 'invitation refused'), ('mint', 'executor token minted'), ('mint_refused', 'executor token refused'), ('signup', 'signed up'), ('signup_refused', 'sign-up refused'), ('email_verified', 'email address verified'), ('reauthentication', 'reauthenticated'), ('password_changed', 'password changed'), ('password_reset_requested', 'password reset requested'), ('password_reset', 'password reset'), ('password_pwned', 'password known to Have I Been Pwned'), ('email_changed', 'email address changed'), ('new_device', 'signed in from an unseen device'), ('turnstile_demanded', 'address must now solve Turnstile'), ('google_refused', 'Google sign-in refused'), ('google_connected', 'Google account connected'), ('google_disconnected', 'Google account disconnected'), ('mfa_enrolled', 'authenticator added'), ('mfa_removed', 'authenticator removed'), ('mfa_reset', 'recovery codes regenerated'), ('mfa_failed', 'second factor refused'), ('sessions_ended', 'other sessions signed out')], db_index=True, max_length=32),
        ),
    ]
